# Generated by Django 6.0.3 on 2026-07-29 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_dh_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_button_label', models.CharField(default='View Map', verbose_name='First Button Label')),
                ('second_button_label', models.CharField(default='View River', verbose_name='Second Button Label')),
                ('first_button_map', models.ForeignKey(limit_choices_to=models.Q(('published', True)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_first_button', to='django_dh_map.map', verbose_name='First Button Map')),
                ('second_button_map', models.ForeignKey(limit_choices_to=models.Q(('published', True)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_second_button', to='django_dh_map.panoramaimagemap', verbose_name='Second Button Map')),
            ],
            options={
                'verbose_name': 'Home Page',
                'db_table': 'stsailes_narratives_home_page',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentitem')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_item', to='stsailes_narratives_app.homepage')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'db_table': 'stsailes_narratives_ci_home_page',
            },
            bases=('django_dh_map.contentitem',),
        ),
    ]
