"""
Django settings for stsailes_narratives_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from environ import FileAwareEnv
from dotenv import load_dotenv, find_dotenv
from glob import glob

env = FileAwareEnv()
load_dotenv(find_dotenv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = '/media'
STATIC_ROOT = BASE_DIR / 'static/'
STATICFILES_DIRS = [
    '/static-vite',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-0lgov2k26n+=bjocstuna-@888$&g3(xvxugltqd*xx+z=_p1=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django_dh_map',
    'stsailes_narratives_app',
    'admin_interface',
    'colorfield',
    'nested_admin',
    'django_jsonform',
    'adminsortable2',
    'solo',
    'tinymce',
    'admin_async_upload',
    'imagekit',
    'django_rq',
    'django.contrib.gis',
    'django.contrib.postgres',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'health_check',
    'cache_cleaner',
    'django_cleanup.apps.CleanupConfig',
    'polymorphic',
    'rest_framework',
    'rest_framework_gis',
    'django_vite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stsailes_narratives_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stsailes_narratives_app.context_processors.get_git_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'stsailes_narratives_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'HOST': env('DB_HOST', default=''),
        'NAME': env('DB_NAME', default=''),
        'USER': env('DB_USER', default=''),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'PORT': env.int('DB_PORT', default=5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'America/Vancouver'

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

# default upload permissions
MEDIA_FOLDER_UID=env.int('MEDIA_FOLDER_UID', default=101)
MEDIA_FOLDER_GID=env.int('MEDIA_FOLDER_GID', default=101)
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755
FILE_UPLOAD_PERMISSIONS = 0o644

# email host
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=1025)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

# CSRF form settings
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['http://localhost:8080', 'http://localhost:5173'])

# iframe settings
X_FRAME_OPTIONS = 'SAMEORIGIN'
SILENCED_SYSTEM_CHECKS = ['security.W019']

GIT_REPO = 'https://github.com/sfu-dhil/stsailes-narratives'
GIT_COMMIT = env('GIT_COMMIT', default='')
GIT_COMMIT_SHORT = env('GIT_COMMIT_SHORT', default='')
GIT_BRANCH = env('GIT_BRANCH', default='')
GIT_TAG = env('GIT_TAG', default='')

# logout redirection
LOGIN_URL = 'admin:login'
LOGIN_REDIRECT_URL = 'admin:index'
LOGOUT_REDIRECT_URL = 'admin:login'

DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "static_url_prefix": "dist",
    }
}

# max uploads/data
DATA_UPLOAD_MAX_MEMORY_SIZE = 256 * 1024 * 1024 # 256MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 256 * 1024 * 1024 # 256MB

# Caches
ONE_MINUTE = 60
ONE_HOUR = ONE_MINUTE * 60
ONE_DAY = ONE_HOUR * 24
ONE_WEEK = ONE_DAY * 7
ONE_MONTH = ONE_DAY * 30
ONE_YEAR = ONE_DAY * 365
CACHE_SECONDS = 1 if DEBUG else env('CACHE_SECONDS', default=ONE_WEEK) # 1 second if debugging else default 1 week
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/django-cache',
    }
}

# django rest framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly'
    ]
}

# background jobs
RQ_SHOW_ADMIN_LINK = True
RQ_QUEUES = {
    'default': {
        'HOST': env('REDIS_HOST', default=''),
        'PORT': env.int('REDIS_PORT', default=6379),
        'DB': env.int('REDIS_DB', default=0),
        'DEFAULT_TIMEOUT': env.int('REDIS_DEFAULT_TIMEOUT', default=(30 * ONE_MINUTE)),
    }
}

# tinymce settings
TINYMCE_DEFAULT_CONFIG = {
    'height': '250px',
    'branding': False,
    'menubar': False,
    'plugins': 'autolink, code, link, anchor, lists, advlist, table, quickbars, wordcount, pagebreak, nonbreaking',
    'toolbar': 'undo redo | numlist bullist | styles | fontsize | alignleft aligncenter alignright | link anchor | hr | removeformat',
    'quickbars_insert_toolbar': False,
    'quickbars_selection_toolbar': 'bold italic underline strikethrough | styles | fontsize | forecolor | blockquote',
    'contextmenu': 'undo redo | inserttable | cell row column deletetable',
    'content_css': 'https://cdn.jsdelivr.net/npm/bootstrap@5.3/dist/css/bootstrap.min.css',
    'content_style': "body { padding: 10px !important; font-family: 'First Nations Unicode', sans-serif; }",
    'valid_elements': '*[*]',
    'formats': { # replace the default tinymce inline styles with Bootstrap css classes & appropriate tags
        'alignleft': {'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', 'classes' : 'text-start'},
        'aligncenter': {'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', 'classes' : 'text-center'},
        'alignright': {'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', 'classes' : 'text-end'},
        'alignjustify': {'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', 'classes' : 'text-justify'},
        'bold': {'inline' : 'strong'},
        'italic': {'inline' : 'em'},
        'underline': {'inline' : 'u'},
        'sup': {'inline' : 'sup'},
        'sub': {'inline' : 'sub'},
        'strikethrough': {'inline' : 'del'}
    },
    'style_formats': [
        { 'title': 'Headings', 'items': [
            { 'title': 'Heading 1', 'format': 'h1' },
            { 'title': 'Heading 2', 'format': 'h2' },
            { 'title': 'Heading 3', 'format': 'h3' },
            { 'title': 'Heading 4', 'format': 'h4' },
            { 'title': 'Heading 5', 'format': 'h5' },
            { 'title': 'Heading 6', 'format': 'h6' }
        ]},
        { 'title': 'Blocks', 'items': [
            { 'title': 'Paragraph', 'format': 'p' },
            { 'title': 'Blockquote', 'format': 'blockquote' },
            { 'title': 'Div', 'block': 'div', 'wrapper': True }
        ]},
        { 'title': 'Containers', 'items': [
            { 'title': 'Container fluid', 'block': 'div', 'classes': 'container-fluid', 'wrapper': True },
            { 'title': 'Container', 'block': 'div', 'classes': 'container', 'wrapper': True },
            { 'title': 'Section', 'block': 'section', 'wrapper': True },
            { 'title': 'Article', 'block': 'article', 'wrapper': True }
        ]},
        { 'title': 'Lists', 'items': [
            { 'title': 'Unstyled List', 'selector': 'ul', 'classes': 'list-unstyled' },
            { 'title': 'Inline List', 'selector': 'ul', 'classes': 'list-inline' },
            { 'title': 'Inline Item', 'selector': 'li', 'classes': 'list-inline-item' },
            { 'title': 'List Group', 'selector': 'ul', 'classes': 'list-group' },
            { 'title': 'List Group Item', 'selector': 'li', 'classes': 'list-group-item' }
        ]},
    ],
    'style_formats_merge': False,
    'style_formats_autohide': True,
}

# GDAL & GEOS paths
# (alphine installs it in `/usr/lib/` with a major version number or full version number)
GDAL_LIBRARY_PATH = glob('/usr/lib/libgdal.so.*')[0]
GEOS_LIBRARY_PATH = glob('/usr/lib/libgeos_c.so.*')[0]